from django.forms import ModelForm
from django import forms
from registro.models import Cuestionario

class CuestionarioForm(ModelForm):
    class Meta:
        S_CHOICES=(('M','Masculino'),('F','Femenino'))
        P_CHOICES=(('1','V'),('0','F'))
        model = Cuestionario
        fields = ['edad', 'sexo', 'carrera', 'p1','p2','p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10',
                'p11', 'p12', 'p13', 'p14', 'p15', 'p16', 'p17', 'p18', 'p19', 'p20',
                'p21', 'p22', 'p23', 'p24', 'p25', 'p26', 'p27', 'p28', 'p29', 'p30',
                'p31', 'p32', 'p33', 'p34', 'p35', 'p36', 'p37', 'p38', 'p39', 'p40',
                'p41', 'p42', 'p43', 'p44', 'p45', 'p46', 'p47', 'p48', 'p49', 'p50',
                'p51', 'p52', 'p53', 'p54', 'p55', 'p56', 'p57', 'p58', 'p59', 'p60',
                'p61', 'p62', 'p63', 'p64', 'p65', 'p66', 'p67', 'p68', 'p69', 'p70',
                'p71', 'p72', 'p73', 'p74', 'p75', 'p76', 'p77', 'p78', 'p79', 'p80',
                'p81', 'p82', 'p83', 'p84', 'p85', 'p86', 'p87', 'p88', 'p89', 'p90',
                'p91', 'p92', 'p93', 'p94', 'p95', 'p96', 'p97', 'p98', 'p99', 'p100',
                'p101', 'p102', 'p103', 'p104', 'p105', 'p106', 'p107', 'p108', 'p109', 'p110',
                'p111', 'p112', 'p113', 'p114', 'p115', 'p116', 'p117', 'p118', 'p119', 'p120',
                'p121', 'p122', 'p123', 'p124', 'p125', 'p126', 'p127', 'p128', 'p129', 'p130',
                'p131', 'p132', 'p133', 'p134', 'p135', 'p136', 'p137', 'p138', 'p139', 'p140',
                'p141', 'p142', 'p143', 'p144', 'p145', 'p146', 'p147', 'p148', 'p149', 'p150',
                'p151', 'p152', 'p153', 'p154', 'p155', 'p156', 'p157', 'p158']
        widgets = {
            'sexo': forms.RadioSelect(choices=S_CHOICES),
            'p1': forms.RadioSelect(choices=P_CHOICES),'p2': forms.RadioSelect(choices=P_CHOICES),
            'p3': forms.RadioSelect(choices=P_CHOICES),'p4': forms.RadioSelect(choices=P_CHOICES),
            'p5': forms.RadioSelect(choices=P_CHOICES), 'p6': forms.RadioSelect(choices=P_CHOICES),
            'p7': forms.RadioSelect(choices=P_CHOICES), 'p8': forms.RadioSelect(choices=P_CHOICES),
            'p9': forms.RadioSelect(choices=P_CHOICES), 'p10': forms.RadioSelect(choices=P_CHOICES),
            'p11': forms.RadioSelect(choices=P_CHOICES), 'p12': forms.RadioSelect(choices=P_CHOICES),
            'p13': forms.RadioSelect(choices=P_CHOICES), 'p14': forms.RadioSelect(choices=P_CHOICES),
            'p15': forms.RadioSelect(choices=P_CHOICES), 'p16': forms.RadioSelect(choices=P_CHOICES),
            'p17': forms.RadioSelect(choices=P_CHOICES), 'p18': forms.RadioSelect(choices=P_CHOICES),
            'p19': forms.RadioSelect(choices=P_CHOICES), 'p20': forms.RadioSelect(choices=P_CHOICES),
            'p21': forms.RadioSelect(choices=P_CHOICES), 'p22': forms.RadioSelect(choices=P_CHOICES),
            'p23': forms.RadioSelect(choices=P_CHOICES), 'p24': forms.RadioSelect(choices=P_CHOICES),
            'p25': forms.RadioSelect(choices=P_CHOICES), 'p26': forms.RadioSelect(choices=P_CHOICES),
            'p27': forms.RadioSelect(choices=P_CHOICES), 'p28': forms.RadioSelect(choices=P_CHOICES),
            'p29': forms.RadioSelect(choices=P_CHOICES), 'p30': forms.RadioSelect(choices=P_CHOICES),
            'p31': forms.RadioSelect(choices=P_CHOICES), 'p32': forms.RadioSelect(choices=P_CHOICES),
            'p33': forms.RadioSelect(choices=P_CHOICES), 'p34': forms.RadioSelect(choices=P_CHOICES),
            'p35': forms.RadioSelect(choices=P_CHOICES), 'p36': forms.RadioSelect(choices=P_CHOICES),
            'p37': forms.RadioSelect(choices=P_CHOICES), 'p38': forms.RadioSelect(choices=P_CHOICES),
            'p39': forms.RadioSelect(choices=P_CHOICES), 'p40': forms.RadioSelect(choices=P_CHOICES),
            'p41': forms.RadioSelect(choices=P_CHOICES), 'p42': forms.RadioSelect(choices=P_CHOICES),
            'p43': forms.RadioSelect(choices=P_CHOICES), 'p44': forms.RadioSelect(choices=P_CHOICES),
            'p45': forms.RadioSelect(choices=P_CHOICES), 'p46': forms.RadioSelect(choices=P_CHOICES),
            'p47': forms.RadioSelect(choices=P_CHOICES), 'p48': forms.RadioSelect(choices=P_CHOICES),
            'p49': forms.RadioSelect(choices=P_CHOICES), 'p50': forms.RadioSelect(choices=P_CHOICES),
            'p51': forms.RadioSelect(choices=P_CHOICES), 'p52': forms.RadioSelect(choices=P_CHOICES),
            'p53': forms.RadioSelect(choices=P_CHOICES), 'p54': forms.RadioSelect(choices=P_CHOICES),
            'p55': forms.RadioSelect(choices=P_CHOICES), 'p56': forms.RadioSelect(choices=P_CHOICES),
            'p57': forms.RadioSelect(choices=P_CHOICES), 'p58': forms.RadioSelect(choices=P_CHOICES),
            'p59': forms.RadioSelect(choices=P_CHOICES), 'p60': forms.RadioSelect(choices=P_CHOICES),
            'p61': forms.RadioSelect(choices=P_CHOICES), 'p62': forms.RadioSelect(choices=P_CHOICES),
            'p63': forms.RadioSelect(choices=P_CHOICES), 'p64': forms.RadioSelect(choices=P_CHOICES),
            'p65': forms.RadioSelect(choices=P_CHOICES), 'p66': forms.RadioSelect(choices=P_CHOICES),
            'p67': forms.RadioSelect(choices=P_CHOICES), 'p68': forms.RadioSelect(choices=P_CHOICES),
            'p69': forms.RadioSelect(choices=P_CHOICES), 'p70': forms.RadioSelect(choices=P_CHOICES),
            'p71': forms.RadioSelect(choices=P_CHOICES), 'p72': forms.RadioSelect(choices=P_CHOICES),
            'p73': forms.RadioSelect(choices=P_CHOICES), 'p74': forms.RadioSelect(choices=P_CHOICES),
            'p75': forms.RadioSelect(choices=P_CHOICES), 'p76': forms.RadioSelect(choices=P_CHOICES),
            'p77': forms.RadioSelect(choices=P_CHOICES), 'p78': forms.RadioSelect(choices=P_CHOICES),
            'p79': forms.RadioSelect(choices=P_CHOICES), 'p80': forms.RadioSelect(choices=P_CHOICES),
            'p81': forms.RadioSelect(choices=P_CHOICES), 'p82': forms.RadioSelect(choices=P_CHOICES),
            'p83': forms.RadioSelect(choices=P_CHOICES), 'p84': forms.RadioSelect(choices=P_CHOICES),
            'p85': forms.RadioSelect(choices=P_CHOICES), 'p86': forms.RadioSelect(choices=P_CHOICES),
            'p87': forms.RadioSelect(choices=P_CHOICES), 'p88': forms.RadioSelect(choices=P_CHOICES),
            'p89': forms.RadioSelect(choices=P_CHOICES), 'p90': forms.RadioSelect(choices=P_CHOICES),
            'p91': forms.RadioSelect(choices=P_CHOICES), 'p92': forms.RadioSelect(choices=P_CHOICES),
            'p93': forms.RadioSelect(choices=P_CHOICES), 'p94': forms.RadioSelect(choices=P_CHOICES),
            'p95': forms.RadioSelect(choices=P_CHOICES), 'p96': forms.RadioSelect(choices=P_CHOICES),
            'p97': forms.RadioSelect(choices=P_CHOICES), 'p98': forms.RadioSelect(choices=P_CHOICES),
            'p99': forms.RadioSelect(choices=P_CHOICES), 'p100': forms.RadioSelect(choices=P_CHOICES),
            'p101': forms.RadioSelect(choices=P_CHOICES), 'p102': forms.RadioSelect(choices=P_CHOICES),
            'p103': forms.RadioSelect(choices=P_CHOICES), 'p104': forms.RadioSelect(choices=P_CHOICES),
            'p105': forms.RadioSelect(choices=P_CHOICES), 'p106': forms.RadioSelect(choices=P_CHOICES),
            'p107': forms.RadioSelect(choices=P_CHOICES), 'p108': forms.RadioSelect(choices=P_CHOICES),
            'p109': forms.RadioSelect(choices=P_CHOICES), 'p110': forms.RadioSelect(choices=P_CHOICES),
            'p111': forms.RadioSelect(choices=P_CHOICES), 'p112': forms.RadioSelect(choices=P_CHOICES),
            'p113': forms.RadioSelect(choices=P_CHOICES), 'p114': forms.RadioSelect(choices=P_CHOICES),
            'p115': forms.RadioSelect(choices=P_CHOICES), 'p116': forms.RadioSelect(choices=P_CHOICES),
            'p117': forms.RadioSelect(choices=P_CHOICES), 'p118': forms.RadioSelect(choices=P_CHOICES),
            'p119': forms.RadioSelect(choices=P_CHOICES), 'p120': forms.RadioSelect(choices=P_CHOICES),
            'p121': forms.RadioSelect(choices=P_CHOICES), 'p122': forms.RadioSelect(choices=P_CHOICES),
            'p123': forms.RadioSelect(choices=P_CHOICES), 'p124': forms.RadioSelect(choices=P_CHOICES),
            'p125': forms.RadioSelect(choices=P_CHOICES), 'p126': forms.RadioSelect(choices=P_CHOICES),
            'p127': forms.RadioSelect(choices=P_CHOICES), 'p128': forms.RadioSelect(choices=P_CHOICES),
            'p129': forms.RadioSelect(choices=P_CHOICES), 'p130': forms.RadioSelect(choices=P_CHOICES),
            'p131': forms.RadioSelect(choices=P_CHOICES), 'p132': forms.RadioSelect(choices=P_CHOICES),
            'p133': forms.RadioSelect(choices=P_CHOICES), 'p134': forms.RadioSelect(choices=P_CHOICES),
            'p135': forms.RadioSelect(choices=P_CHOICES), 'p136': forms.RadioSelect(choices=P_CHOICES),
            'p137': forms.RadioSelect(choices=P_CHOICES), 'p138': forms.RadioSelect(choices=P_CHOICES),
            'p139': forms.RadioSelect(choices=P_CHOICES), 'p140': forms.RadioSelect(choices=P_CHOICES),
            'p141': forms.RadioSelect(choices=P_CHOICES), 'p142': forms.RadioSelect(choices=P_CHOICES),
            'p143': forms.RadioSelect(choices=P_CHOICES), 'p144': forms.RadioSelect(choices=P_CHOICES),
            'p145': forms.RadioSelect(choices=P_CHOICES), 'p146': forms.RadioSelect(choices=P_CHOICES),
            'p147': forms.RadioSelect(choices=P_CHOICES), 'p148': forms.RadioSelect(choices=P_CHOICES),
            'p149': forms.RadioSelect(choices=P_CHOICES), 'p150': forms.RadioSelect(choices=P_CHOICES),
            'p151': forms.RadioSelect(choices=P_CHOICES), 'p152': forms.RadioSelect(choices=P_CHOICES),
            'p153': forms.RadioSelect(choices=P_CHOICES), 'p154': forms.RadioSelect(choices=P_CHOICES),
            'p155': forms.RadioSelect(choices=P_CHOICES), 'p156': forms.RadioSelect(choices=P_CHOICES),
            'p157': forms.RadioSelect(choices=P_CHOICES), 'p158': forms.RadioSelect(choices=P_CHOICES)
        }