# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime

class Cuestionario(models.Model):
    E_CHOICES=(('15','15'),('16','16'),('17','17'),('18','18'),('19','19'),('20','20'),('21','21'),('22','22'))
    C_CHOICES=(('Administracion','Administracion'),('Obstetricia','Obstetricia'),('Ing. de Sistemas','Ing. de Sistemas'),('Ing. Civil','Ing. Civil'),('Ing. Ambiental','Ing. Ambiental'))
    edad = models.CharField(max_length=2,choices=E_CHOICES)
    sexo = models.CharField(max_length=2)
    carrera = models.CharField(max_length=20,choices=C_CHOICES)
    p1 = models.IntegerField()
    p2 = models.IntegerField()
    p3 = models.IntegerField()
    p4 = models.IntegerField()
    p5 = models.IntegerField()
    p6 = models.IntegerField()
    p7 = models.IntegerField()
    p8 = models.IntegerField()
    p9 = models.IntegerField()
    p10 = models.IntegerField()
    p11 = models.IntegerField()
    p12 = models.IntegerField()
    p13 = models.IntegerField()
    p14 = models.IntegerField()
    p15 = models.IntegerField()
    p16 = models.IntegerField()
    p17 = models.IntegerField()
    p18 = models.IntegerField()
    p19 = models.IntegerField()
    p20 = models.IntegerField()
    p21 = models.IntegerField()
    p22 = models.IntegerField()
    p23 = models.IntegerField()
    p24 = models.IntegerField()
    p25 = models.IntegerField()
    p26 = models.IntegerField()
    p27 = models.IntegerField()
    p28 = models.IntegerField()
    p29 = models.IntegerField()
    p30 = models.IntegerField()
    p31 = models.IntegerField()
    p32 = models.IntegerField()
    p33 = models.IntegerField()
    p34 = models.IntegerField()
    p35 = models.IntegerField()
    p36 = models.IntegerField()
    p37 = models.IntegerField()
    p38 = models.IntegerField()
    p39 = models.IntegerField()
    p40 = models.IntegerField()
    p41 = models.IntegerField()
    p42 = models.IntegerField()
    p43 = models.IntegerField()
    p44 = models.IntegerField()
    p45 = models.IntegerField()
    p46 = models.IntegerField()
    p47 = models.IntegerField()
    p48 = models.IntegerField()
    p49 = models.IntegerField()
    p50 = models.IntegerField()
    p51 = models.IntegerField()
    p52 = models.IntegerField()
    p53 = models.IntegerField()
    p54 = models.IntegerField()
    p55 = models.IntegerField()
    p56 = models.IntegerField()
    p57 = models.IntegerField()
    p58 = models.IntegerField()
    p59 = models.IntegerField()
    p60 = models.IntegerField()
    p61 = models.IntegerField()
    p62 = models.IntegerField()
    p63 = models.IntegerField()
    p64 = models.IntegerField()
    p65 = models.IntegerField()
    p66 = models.IntegerField()
    p67 = models.IntegerField()
    p68 = models.IntegerField()
    p69 = models.IntegerField()
    p70 = models.IntegerField()
    p71 = models.IntegerField()
    p72 = models.IntegerField()
    p73 = models.IntegerField()
    p74 = models.IntegerField()
    p75 = models.IntegerField()
    p76 = models.IntegerField()
    p77 = models.IntegerField()
    p78 = models.IntegerField()
    p79 = models.IntegerField()
    p80 = models.IntegerField()
    p81 = models.IntegerField()
    p82 = models.IntegerField()
    p83 = models.IntegerField()
    p84 = models.IntegerField()
    p85 = models.IntegerField()
    p86 = models.IntegerField()
    p87 = models.IntegerField()
    p88 = models.IntegerField()
    p89 = models.IntegerField()
    p90 = models.IntegerField()
    p91 = models.IntegerField()
    p92 = models.IntegerField()
    p93 = models.IntegerField()
    p94 = models.IntegerField()
    p95 = models.IntegerField()
    p96 = models.IntegerField()
    p97 = models.IntegerField()
    p98 = models.IntegerField()
    p99 = models.IntegerField()
    p100 = models.IntegerField()
    p101 = models.IntegerField()
    p102 = models.IntegerField()
    p103 = models.IntegerField()
    p104 = models.IntegerField()
    p105 = models.IntegerField()
    p106 = models.IntegerField()
    p107 = models.IntegerField()
    p108 = models.IntegerField()
    p109 = models.IntegerField()
    p110 = models.IntegerField()
    p111 = models.IntegerField()
    p112 = models.IntegerField()
    p113 = models.IntegerField()
    p114 = models.IntegerField()
    p115 = models.IntegerField()
    p116 = models.IntegerField()
    p117 = models.IntegerField()
    p118 = models.IntegerField()
    p119 = models.IntegerField()
    p120 = models.IntegerField()
    p121 = models.IntegerField()
    p122 = models.IntegerField()
    p123 = models.IntegerField()
    p124 = models.IntegerField()
    p125 = models.IntegerField()
    p126 = models.IntegerField()
    p127 = models.IntegerField()
    p128 = models.IntegerField()
    p129 = models.IntegerField()
    p130 = models.IntegerField()
    p131 = models.IntegerField()
    p132 = models.IntegerField()
    p133 = models.IntegerField()
    p134 = models.IntegerField()
    p135 = models.IntegerField()
    p136 = models.IntegerField()
    p137 = models.IntegerField()
    p138 = models.IntegerField()
    p139 = models.IntegerField()
    p140 = models.IntegerField()
    p141 = models.IntegerField()
    p142 = models.IntegerField()
    p143 = models.IntegerField()
    p144 = models.IntegerField()
    p145 = models.IntegerField()
    p146 = models.IntegerField()
    p147 = models.IntegerField()
    p148 = models.IntegerField()
    p149 = models.IntegerField()
    p150 = models.IntegerField()
    p151 = models.IntegerField()
    p152 = models.IntegerField()
    p153 = models.IntegerField()
    p154 = models.IntegerField()
    p155 = models.IntegerField()
    p156 = models.IntegerField()
    p157 = models.IntegerField()
    p158 = models.IntegerField()
    fecha = models.DateTimeField(default=datetime.datetime.now())
    trastorno_final = models.CharField(max_length=20, blank=True)
    indicador = models.CharField(max_length=10, blank=True)
    def __unicode__(self):
        return str(self.pk)

class PuntajeTrastorno(models.Model):
    nombre_trastorno = models.CharField(max_length=20)
    puntaje_trastorno = models.IntegerField()
    registro = models.ForeignKey(Cuestionario, editable=False)
    def __unicode__(self):
        return self.nombre_trastorno

class BRMF(models.Model):
    y = models.IntegerField(null=True)
    z = models.IntegerField(null=True)
    uno = models.IntegerField(null=True)
    dos = models.IntegerField(null=True)
    tres = models.IntegerField(null=True)
    cuatro  = models.IntegerField(null=True)
    cinco  = models.IntegerField(null=True)
    seis_a = models.IntegerField(null=True)
    seis_b = models.IntegerField(null=True)
    siete = models.IntegerField(null=True)
    ocho_a = models.IntegerField(null=True)
    ocho_b = models.IntegerField(null=True)
    s = models.IntegerField(null=True)
    c = models.IntegerField(null=True)
    p = models.IntegerField(null=True)
    a = models.IntegerField(null=True)
    d = models.IntegerField(null=True)
    sexobr = models.CharField(max_length=1)
    def __unicode__(self):
        return str(self.pk)





