# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 19:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeTrastorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trastorno', models.CharField(max_length=20)),
                ('puntaje_trastorno', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='registro',
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 14, 14, 29, 56, 170000)),
        ),
        migrations.DeleteModel(
            name='Proceso',
        ),
        migrations.AddField(
            model_name='puntajetrastorno',
            name='registro',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='registro.Cuestionario'),
        ),
    ]
